"use client";

import { Link } from "@/components/ui/Link";
import { usePlugPay } from "@/store/context";
import { codeOf } from "@/lib/shared";
import { PublicShellX } from "@/components/layout/PublicShellX";
import { ErrorState } from "@/components/ui/ErrorState";
import { openWhatsApp, reviewStatus, sellerBadgeInfo, timeLeft } from "@/lib/seller";
import { Ic } from "@/components/ui/Ic";
import { DocTrader } from "@/components/seller/sales/DocTrader";
import { DocBadges } from "@/components/seller/sales/DocBadges";
import { DocItems } from "@/components/seller/sales/DocItems";

/* ---- Buyer-facing links: public receipt, review, pay invoice ---- */
/* ---- Buyer-facing links: public receipt, review, pay invoice ---- */
export function PublicReceiptPage(props) {
  var pp = usePlugPay();
  var code = codeOf(props.code);
  var sale = pp.receiptsList.filter(function (r) {
    return codeOf(r.code) === code;
  })[0];
  if (!sale || !sale.sentAt)
    return (
      <PublicShellX title="Receipt not found">
        <ErrorState
          icon="receipt"
          title="Receipt unavailable"
          sub="This receipt link is no longer valid."
          backTo="/"
          backLabel="Return home"
        />
      </PublicShellX>
    );
  var sp = pp.sellerProfile,
    badges = sellerBadgeInfo(pp),
    st = reviewStatus(sale);
  return (
    <PublicShellX title="PlugPay receipt" subtitle={sp.bizName + " \u00b7 " + sale.code}>
      <div className="doc-wrap">
        <div className="doc-card">
          <div className="doc-thanks">
            <div className="ic-big">{Ic("badge-check", 24)}</div>
            <h3>{"Thank you for shopping with " + sp.bizName + "!"}</h3>
            <p>{"Your payment of KSh " + sale.total.toLocaleString() + " was received and confirmed."}</p>
          </div>
          <DocTrader sp={sp} />
          <DocBadges badges={badges} />
          <div className="doc-sec">
            <div className="doc-sec-h">{Ic("credit-card", 13)}Payment confirmation</div>
            <div className="doc-row">
              <span>Receipt no.</span>
              <strong>{sale.code}</strong>
            </div>
            <div className="doc-row">
              <span>Payment ref</span>
              <strong>{sale.paymentRef || "\u2014"}</strong>
            </div>
            <div className="doc-row">
              <span>Date</span>
              <strong>{new Date(sale.createdAt).toLocaleString()}</strong>
            </div>
            <div className="doc-row">
              <span>Buyer phone</span>
              <strong>{sale.buyerPhone}</strong>
            </div>
          </div>
          <DocItems items={sale.items} />
          <div className="doc-total-row">
            <span>Total paid</span>
            <strong>{"KSh " + sale.total.toLocaleString()}</strong>
          </div>
          <div className="doc-review">
            <div className="doc-review-ic">{Ic("star", 16)}</div>
            <div className="doc-review-txt">
              {st.state === "open" ? (
                <>
                  <b>How was your experience?</b>
                  {"Rate " + sp.bizName + ". This link closes in " + timeLeft(st.msLeft) + "."}
                </>
              ) : st.state === "done" ? (
                <>
                  <b>Thanks for your review</b>
                  {"You rated this purchase " + sale.review.rating + " of 5."}
                </>
              ) : (
                <>
                  <b>Review window closed</b>Reviews can be left within 6 hours of receiving the receipt.
                </>
              )}
            </div>
          </div>
          <div className="doc-actions">
            {st.state === "open" && (
              <Link to={"/review/" + code} className="es-btn">
                {Ic("star", 14)}Leave a review
              </Link>
            )}
            <button
              className="es-btn alt"
              onClick={function () {
                openWhatsApp(
                  sp.whatsapp || sp.phone,
                  "Hi " + sp.bizName + ", I have a question about my order " + sale.code,
                );
              }}
            >
              {Ic("message-circle", 14)}Message seller
            </button>
          </div>
          <div className="doc-note">
            {"This receipt was generated by PlugPay on behalf of " +
              sp.bizName +
              ". Keep it as proof of payment."}
          </div>
        </div>
      </div>
    </PublicShellX>
  );
}